*** Settings ***
Library    Selenium2Library
Library    DateTime

*** Variable ***
#information
${TestResult_Seasonal_Campaign_API}     ${EXECDIR}${/}Seasonal_Campaign_API.json
${Url_Create_Campaigns}           https://uatcreator.the1.co.th/mnt/overlay/wcm/core/content/sites/createpagewizard.html/content/the1/campaigns
${Campain_Start Date_AEM}           October 01, 2020
${Campain_End Date_AEM}             October 31, 2031
${badge_1_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/1redeemnotstart_aug
${badge_2_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/1transfer1redeemspender-aug
${badge_3_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/1transferexpiry_aug
${badge_4_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/2transfer2redeemaug0
${badge_5_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_update_emailmobilev3
${badge_6_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_update_emailmobilewebappsep
${badge_7_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_update_emailmobilewebsep
${badge_8_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_update_emailormobileappsep
${badge_9_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_update_emailormobilewebappsep
${badge_10_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_update_emailormobilewebsep
${badge_11_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_update_emailwebappsep
${badge_12_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_update_emailwebsep0
${Article_TH_1_Seasonal_Campaign_AEM}             /content/the1/api/th/th/articles/test_article_1
${Article_TH_2_Seasonal_Campaign_AEM}             /content/the1/api/th/th/articles/test_article_2
${Article_TH_3_Seasonal_Campaign_AEM}             /content/the1/api/th/th/articles/test_article_3
${Article_TH_4_Seasonal_Campaign_AEM}             /content/the1/api/th/th/articles/test_article_4
${Article_TH_5_Seasonal_Campaign_AEM}             /content/the1/api/th/th/articles/test_article_5
${Article_TH_6_Seasonal_Campaign_AEM}             /content/the1/api/th/th/articles/test_article_6
${Article_TH_7_Seasonal_Campaign_AEM}             /content/the1/api/th/th/articles/test_article_7
${Article_TH_8_Seasonal_Campaign_AEM}             /content/the1/api/th/th/articles/test_article_8
${Article_TH_9_Seasonal_Campaign_AEM}             /content/the1/api/th/th/articles/test_article_9
${Article_TH_10_Seasonal_Campaign_AEM}             /content/the1/api/th/th/articles/test_article_10
${Article_EN_1_Seasonal_Campaign_AEM}              /content/the1/api/th/en/articles/test_article_1
${Article_EN_2_Seasonal_Campaign_AEM}              /content/the1/api/th/en/articles/test_article_2
${Article_EN_3_Seasonal_Campaign_AEM}              /content/the1/api/th/en/articles/test_article_3
${Article_EN_4_Seasonal_Campaign_AEM}              /content/the1/api/th/en/articles/test_article_4
${Article_EN_5_Seasonal_Campaign_AEM}              /content/the1/api/th/en/articles/test_article_5
${Article_EN_6_Seasonal_Campaign_AEM}              /content/the1/api/th/en/articles/test_article_6
${Article_EN_7_Seasonal_Campaign_AEM}              /content/the1/api/th/en/articles/test_article_7
${Article_EN_8_Seasonal_Campaign_AEM}              /content/the1/api/th/en/articles/test_article_8
${Article_EN_9_Seasonal_Campaign_AEM}              /content/the1/api/th/en/articles/test_article_9
${Article_EN_10_Seasonal_Campaign_AEM}              /content/the1/api/th/en/articles/test_article_10
#PROD

#${Url_Create_Campaigns}           https://creator.the1.co.th/mnt/overlay/wcm/core/content/sites/createpagewizard.html/content/the1/campaigns
#${badge_1_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_tuesdaytastyoct
#${badge_2_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_twdlover_jun
#${badge_3_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_twdx3_jun
#${badge_4_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_valentine_giftpointv2
#${badge_5_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_valentine_nightv2
#${badge_6_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_wednesdaywisdomoct
#${badge_7_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_weekday_shopperv2
#${badge_8_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_welcomeback_jun
#${badge_9_Seasonal_Campaign_AEM}                 /content/the1/badgesv2/bdg_wonderful_weekday
#${badge_10_Seasonal_Campaign_AEM}                /content/the1/badgesv2/bdg_wranglerloversep
#${badge_11_Seasonal_Campaign_AEM}                /content/the1/badgesv2/bdg_yanggoong_aug
#${badge_12_Seasonal_Campaign_AEM}                /content/the1/badgesv2/bdg_zeenzonehalloweenoct
#${Article_TH_1_Seasonal_Campaign_AEM}             /content/the1/api/th/th/t1x-privilege/shopping/Office_Mate
#${Article_TH_2_Seasonal_Campaign_AEM}             /content/the1/api/th/th/t1x-privilege/shopping/b2s
#${Article_TH_3_Seasonal_Campaign_AEM}             /content/the1/api/th/th/t1x-privilege/shopping/baan---beyond
#${Article_TH_4_Seasonal_Campaign_AEM}             /content/the1/api/th/th/t1x-privilege/shopping/central-department-store
#${Article_TH_5_Seasonal_Campaign_AEM}             /content/the1/api/th/th/t1x-privilege/shopping/central-department-store1
#${Article_TH_6_Seasonal_Campaign_AEM}             /content/the1/api/th/th/t1x-privilege/shopping/central-department-store11
#${Article_TH_7_Seasonal_Campaign_AEM}             /content/the1/api/th/th/t1x-privilege/shopping/central-department-store111
#${Article_TH_8_Seasonal_Campaign_AEM}             /content/the1/api/th/th/t1x-privilege/shopping/central-embassy
#${Article_TH_9_Seasonal_Campaign_AEM}             /content/the1/api/th/th/t1x-privilege/shopping/central-food-hall
#${Article_TH_10_Seasonal_Campaign_AEM}             /content/the1/api/th/th/t1x-privilege/shopping/central-marketing-group
#${Article_EN_1_Seasonal_Campaign_AEM}              /content/the1/api/th/en/t1x-privilege/shopping/Office_Mate
#${Article_EN_2_Seasonal_Campaign_AEM}              /content/the1/api/th/en/t1x-privilege/shopping/b2s
#${Article_EN_3_Seasonal_Campaign_AEM}              /content/the1/api/th/en/t1x-privilege/shopping/baan---beyond
#${Article_EN_4_Seasonal_Campaign_AEM}              /content/the1/api/th/en/t1x-privilege/shopping/central-department-store
#${Article_EN_5_Seasonal_Campaign_AEM}              /content/the1/api/th/en/t1x-privilege/shopping/central-department-store1
#${Article_EN_6_Seasonal_Campaign_AEM}              /content/the1/api/th/en/t1x-privilege/shopping/central-department-store11
#${Article_EN_7_Seasonal_Campaign_AEM}              /content/the1/api/th/en/t1x-privilege/shopping/central-department-store111
#${Article_EN_8_Seasonal_Campaign_AEM}              /content/the1/api/th/en/t1x-privilege/shopping/central-embassy
#${Article_EN_9_Seasonal_Campaign_AEM}              /content/the1/api/th/en/t1x-privilege/shopping/central-food-hall
#${Article_EN_10_Seasonal_Campaign_AEM}             /content/the1/api/th/en/t1x-privilege/shopping/central-marketing-group



${icon_The1_Central_AEM}        xpath=/html[1]/body[1]/coral-shell[1]/coral-shell-content[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[1]/coral-panel-content[1]/div[2]/coral-masonry[1]/coral-masonry-item[1]/div[1]/coral-icon[1]
${icon_Canpaign_AEM}        xpath=/html[1]/body[1]/coral-shell[1]/coral-shell-content[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[1]/coral-panel-content[1]/div[2]/coral-masonry[1]/coral-masonry-item[7]/div[1]/coral-icon[1]
${card_Seasonal_Campaign_AEM}       xpath=/html/body/form/div/coral-panelstack/coral-panel[1]/coral-panel-content/div/div/coral-masonry/coral-masonry-item[7]/coral-card/coral-card-asset/img
${btn_next_card_Seasonal_Campaign_AEM}      xpath=/html[1]/body[1]/form[1]/div[1]/div[1]/coral-panelstack[1]/coral-panel[1]/coral-panel-content[1]/div[1]/button[1]
${input_Campaign_Title_AEM}        xpath=/html[1]/body[1]/form[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[1]/coral-panel-content[1]/div[1]/div[1]/section[1]/div[1]/div[1]/input[1]
${input_Campaign_Name_AEM}        xpath=/html[1]/body[1]/form[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[1]/coral-panel-content[1]/div[1]/div[1]/section[1]/div[2]/input[1]
${input_Campaign_Description_AEM}        xpath=/html[1]/body[1]/form[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[1]/coral-panel-content[1]/div[1]/div[1]/section[1]/div[3]/div[1]/textarea[1]
${tab_Campaign Details_AEM}           xpath=/html[1]/body[1]/form[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-tablist[1]/coral-tab[2]/coral-tab-label[1]
${tab_Campaign Details_Propeties_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-tablist/coral-tab[2]/coral-tab-label
${input_Header Title EN_AEM}           xpath=/html[1]/body[1]/form[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/input[1]
${input_Header Title TH_AEM}           xpath=/html[1]/body[1]/form[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[2]/input[1]
${input_Feature Image - EN_AEM}           xpath=/html[1]/body[1]/form[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[3]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Feature Image - TH_AEM}           xpath=/html[1]/body[1]/form[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Page Start Date_AEM}           xpath=/html[1]/body[1]/form[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[5]/coral-datepicker[1]/input[2]
${input_Page End Date_AEM}           xpath=/html[1]/body[1]/form[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[6]/coral-datepicker[1]/input[2]
${Btn_Create_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/form[1]/div[1]/div[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/button[2]/coral-button-label[1]
${Popup_Seasonal_Campaign_AEM}           xpath=/html/body/coral-dialog/div[2]/coral-dialog-content
${Btn_Open_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/coral-dialog[1]/div[2]/coral-dialog-footer[1]/button[2]/coral-button-label[1]
${btn_Preview_Page_Seasonal_Campaign_AEM}       xpath=/html/body/div[3]/div[2]/div[1]/coral-actionbar/coral-actionbar-secondary/coral-actionbar-item[3]/button/coral-button-label
${Btn_Page_Infomation_Seasonal_Campaign_AEM}           xpath=/html/body/div[3]/div[2]/div[1]/coral-actionbar/coral-actionbar-primary/coral-actionbar-item[2]/a/coral-icon
${Btn_Open_Properties_Seasonal_Campaign_AEM}           xpath=//*[@id="pageinfo-data"]/button[1]/coral-button-label
${select_Type of Campaign_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[1]/coral-select[1]/button[1]
${selected_Type Seasonal Campaign_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[2]
${selected_Type Opt-in Campaign_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[3]
${btn_Add_Type of Content_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/button[1]/coral-button-label[1]
${btn_Add_Type of Content_1_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/button[1]
${input_Free Text - EN_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[6]/div/div[2]/div/div[2]/p
${input_Free Text - TH_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[6]/div/div[3]/div/div[2]/p
${btn_Save&Close_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[1]/coral-actionbar/coral-actionbar-secondary/coral-actionbar-item[2]/coral-buttongroup/button[1]/coral-button-label
${select_Type of Content_1_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[1]/coral-select/button/span

#Image_Type of Content
${selected_Image_Type of Content_1_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[2]
${select_order_Image_1_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[5]/div/div[1]/coral-select/button/span
${selected_order 2_Image_1_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[5]/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[2]
${selected_order 10_Image_1_Seasonal_Campaign_AEM}           xpath=//html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[1]/coral-multifield-item-content/div/div/div[5]/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[10]
${Btn_add_image_EN_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[5]/div/div[2]/coral-multifield/button/coral-button-label
${input_Image-EN 1_Seasonal_Campaign_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[2]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Image-EN 2_Seasonal_Campaign_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[2]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Image-EN 3_Seasonal_Campaign_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[2]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Image-EN 4_Seasonal_Campaign_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[2]/coral-multifield[1]/coral-multifield-item[4]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${Btn_add_image_TH_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[5]/div/div[3]/coral-multifield/button/coral-button-label
${input_Image-TH 1_Seasonal_Campaign_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[3]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Image-TH 2_Seasonal_Campaign_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[3]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Image-TH 3_Seasonal_Campaign_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[3]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${Delete_Image-EN 2_Seasonal_Campaign_AEM}        xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[5]/div/div[2]/coral-multifield/coral-multifield-item[2]/button[1]/coral-icon
${Delete_Image-TH 3_Seasonal_Campaign_AEM}        xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[5]/div/div[3]/coral-multifield/coral-multifield-item[3]/button[1]/coral-icon

#Reward Store_Type of Content
${selected_Reward Store_Type of Content_1_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[3]
${input_Reward Store Title - EN_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[2]/input[1]
${input_Reward Store Title - TH_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[3]/input[1]
${input_Reward Store_Seasonal_Campaign_AEM}                      xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${btn_Add_Type of Content_R1_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/button
${select_order_Free Text_2_Seasonal_Campaign_AEM}           xpath=//html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[2]/coral-multifield-item-content/div/div/div[6]/div/div[1]/coral-select/button/span
${selected_order 2_Free Text_2_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[2]/coral-multifield-item-content/div/div/div[6]/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[2]
${input_Free Text - EN_2_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[2]/coral-multifield-item-content/div/div/div[6]/div/div[2]/div/div[2]/p
${input_Free Text - TH_2_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[2]/coral-multifield-item-content/div/div/div[6]/div/div[3]/div/div[2]/p
${Delete_Free Text_2_Seasonal_Campaign_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[2]/button[1]/coral-icon

#Badge_Type of Content
${selected_Badge_Type of Content_1_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[4]
${select_order_Badge_1_Seasonal_Campaign_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[1]/coral-select[1]/button[1]/span[1]
${selected_order 5_Badge_1_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[5]
${selected_order 1_Badge_1_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[1]
${input_Badge Title - EN_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[2]/input[1]
${input_Badge Title - TH_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[3]/input[1]
${input_Badge Display_Seasonal_Campaign_AEM}                      xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${Delete_Badge Display_1_Seasonal_Campaign_AEM}                      xpath=//body/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[4]/foundation-autocomplete[1]/coral-taglist[1]/coral-tag[1]/button[1]

#Article_Type of Content
${selected_Article_Type of Content_1_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[5]
${input_Article Title - EN_Seasonal_Campaign_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[2]/input[1]
${input_Article Title - TH_Seasonal_Campaign_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[3]/input[1]
${input_Article Page - EN_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Article Page - TH_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[5]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${Delete_Article Page - EN_2_Seasonal_Campaign_AEM}        xpath=//body/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[4]/foundation-autocomplete[1]/coral-taglist[1]/coral-tag[2]/button[1]
${Delete_Article Page - TH_2_Seasonal_Campaign_AEM}        xpath=//body/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[5]/foundation-autocomplete[1]/coral-taglist[1]/coral-tag[2]/button[1]

#Link Out URL_Type of Content
${selected_Link Out URL_Type of Content_1_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[6]
${input_Header - EN_URL_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[2]/input[1]
${input_Header - TH_URL_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[3]/input[1]
${input_URL - EN_URL_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[4]/input[1]
${input_URL - TH_URL_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[5]/input[1]
${input_Free Text - EN_URL_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[6]/div[1]/div[2]/p[1]
${input_Free Text - TH_URL_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[7]/div[1]/div[2]/p[1]

#AEM_Campaign_07 '2  Type of Content'
${btn_Add_1_Type of Content_Campaign_07_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/button/coral-button-label
${select_Type of Content_2_Campaign_07_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/button[1]
${selected_Image_Type of Content_2_Campaign_07_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[2]
${select_order_Image_2_Campaign_07_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[1]/coral-select[1]/button[1]
${selected_order_2_Image_2_Campaign_07_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[2]
${Btn_add_image_EN_Campaign_07_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[2]/coral-multifield[1]/button[1]/coral-button-label[1]
${input_Image-EN 1_Campaign_07_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[2]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${Btn_add_image_TH_Campaign_07_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[3]/coral-multifield[1]/button[1]/coral-button-label[1]
${input_Image-TH 1_Campaign_07_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[3]/coral-multifield[1]/coral-multifield-item[1]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]

#AEM_Campaign_08 '3  Type of Content'
${input_Image-EN 2_Campaign_08_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[2]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Image-EN 3_Campaign_08_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[2]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Image-TH 2_Campaign_08_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[3]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Image-TH 3_Campaign_08_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[2]/coral-multifield-item-content[1]/div[1]/div[1]/div[5]/div[1]/div[3]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${btn_Add_2_Type of Content_Campaign_08_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/button[1]/coral-button-label[1]
${select_Type of Content_3_Campaign_08_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/button[1]
${selected_Reward Store_Type of Content_3_Campaign_08_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[3]
${select_order_Reward Store_3_Campaign_08_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[1]/coral-select[1]/button[1]
${selected_order_3_Reward Store_3_Campaign_08_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[3]
${input_Reward Store Title - EN_Campaign_08_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[2]/input[1]
${input_Reward Store Title - TH_Campaign_08_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[3]/input[1]
${input_Reward Store_Campaign_08_AEM}                      xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
#AEM_Campaign_09 '6  Type of Content'
#Badge#AEM_Campaign_09 '6  Type of Content'
${btn_Add_3_Type of Content_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/button[1]/coral-button-label[1]
${select_Type of Content_4_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[4]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/button[1]
${selected_Badge_Type of Content_4_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[4]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[4]
${select_order_Badge_4_Campaign_09_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[4]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[1]/coral-select[1]/button[1]
${selected_order_4_Badge_4_Campaign_09_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[4]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[4]
${input_Badge Title - EN_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[4]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[2]/input[1]
${input_Badge Title - TH_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[4]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[3]/input[1]
${input_Badge Display_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[4]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]

#Article#AEM_Campaign_09 '6  Type of Content'
${btn_Add_4_Type of Content_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/button[1]
${select_Type of Content_5_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[5]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/button[1]
${selected_Article_Type of Content_5_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[5]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[5]
${select_order_Article_5_Campaign_09_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[5]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[1]/coral-select[1]/button[1]
${selected_order_5_Article_5_Campaign_09_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[5]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[5]
${input_Article Title - EN_Campaign_09_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[5]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[2]/input[1]
${input_Article Title - TH_Campaign_09_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[5]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[3]/input[1]
${input_Article Page - EN_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[5]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Article Page - TH_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[5]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[5]/foundation-autocomplete[1]/div[1]/div[1]/input[1]

#Link Out URL#AEM_Campaign_09 '6  Type of Content'
${btn_Add_5_Type of Content_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/button[1]/coral-button-label[1]
${select_Type of Content_6_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[6]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/button[1]
${selected_Link Out URL_Type of Content_6_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[6]/coral-multifield-item-content[1]/div[1]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[6]
${select_order_Link Out URL_6_Campaign_09_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[6]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[1]/coral-select[1]/button[1]
${selected_order_6_Link Out URL_6_Campaign_09_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[6]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[1]/coral-select[1]/coral-overlay[1]/coral-selectlist[1]/coral-selectlist-item[6]
${input_Header - EN_URL_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[6]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[2]/input[1]
${input_Header - TH_URL_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[6]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[3]/input[1]
${input_URL - EN_URL_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[6]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[4]/input[1]
${input_URL - TH_URL_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[6]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[5]/input[1]
${input_Free Text - EN_URL_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[6]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[6]/div[1]/div[2]/p[1]
${input_Free Text - TH_URL_Campaign_09_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[6]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[7]/div[1]/div[2]/p[1]

#AEM_Campaign_20_Edit Campaign information 6 Type of Content
${Delete_Image-EN 2_Campaign_20_AEM}        xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[2]/coral-multifield-item-content/div/div/div[5]/div/div[2]/coral-multifield/coral-multifield-item[2]/button[1]/coral-icon
${Delete_Image-EN 3_Campaign_20_AEM}        xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[2]/coral-multifield-item-content/div/div/div[5]/div/div[2]/coral-multifield/coral-multifield-item[3]/button[1]/coral-icon
${Delete_Image-TH 2_Campaign_20_AEM}        xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[2]/coral-multifield-item-content/div/div/div[5]/div/div[3]/coral-multifield/coral-multifield-item[2]/button[1]/coral-icon
${Delete_Image-TH 3_Campaign_20_AEM}        xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[2]/coral-multifield-item-content/div/div/div[5]/div/div[3]/coral-multifield/coral-multifield-item[3]/button[1]/coral-icon
${Delete_Badge Display_4_Campaign_20_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[4]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[4]/foundation-autocomplete[1]/coral-taglist[1]/coral-tag[4]/button[1]/coral-button-label[1]
${Delete_Badge Display_3_Campaign_20_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[4]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[4]/foundation-autocomplete[1]/coral-taglist[1]/coral-tag[3]/button[1]/coral-button-label[1]
${Delete_Article_TH_4_Campaign_20_AEM}          xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[5]/coral-multifield-item-content/div/div/div[7]/div/div[5]/foundation-autocomplete/coral-taglist/coral-tag[4]/button/coral-icon
${Delete_Article_EN_4_Campaign_20_AEM}          xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[5]/coral-multifield-item-content/div/div/div[7]/div/div[4]/foundation-autocomplete/coral-taglist/coral-tag[4]/button/coral-icon
${input_Header Title EN_Campaign_20_AEM}         xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[2]/input[1]
${input_Header Title TH_Campaign_20_AEM}         xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[3]/input[1]
${input_Feature Image - EN_Campaign_20_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Feature Image - TH_Campaign_20_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[5]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Page Start Date_Campaign_20_AEM}        xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[6]/coral-datepicker[1]/input[2]
${input_Page End Date_Campaign_20_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[7]/coral-datepicker[1]/input[2]
${input_Free Text - EN_Campaign_20_AEM}         xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[1]/coral-multifield-item-content/div/div/div[6]/div/div[2]/div/div[2]
${input_Free Text - TH_Campaign_20_AEM}         xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[1]/coral-multifield-item-content/div/div/div[6]/div/div[3]/div/div[2]
${select_order_Reward Store_3_Campaign_20_AEM}      xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[1]/coral-select[1]/button[1]
${selected_order_4_Reward Store_3_Campaign_20_AEM}      xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[3]/coral-multifield-item-content/div/div/div[3]/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[4]
${input_Reward Store_Campaign_20_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[3]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${selected_order_6_Badge_4_Campaign_20_AEM}            xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[4]/coral-multifield-item-content/div/div/div[2]/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[6]
${selected_order_3_Link Out URL_6_Campaign_20_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[6]/coral-multifield-item-content/div/div/div[4]/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[3]
${input_Free Text - EN_URL_Campaign_20_AEM}            xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[6]/coral-multifield-item-content/div/div/div[4]/div/div[6]/div/div[2]
${input_Free Text - TH_URL_Campaign_20_AEM}            xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[6]/coral-multifield-item-content/div/div/div[4]/div/div[7]/div/div[2]

#Badge#AEM_Campaign_10 '10  Type of Content'
${btn_Add_6_Type of Content_Campaign_10_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/button/coral-button-label
${select_Type of Content_7_Campaign_10_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[7]/coral-multifield-item-content/div/div/div[1]/coral-select/button/span
${selected_Badge_Type of Content_7_Campaign_10_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[7]/coral-multifield-item-content/div/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[4]
${select_order_Badge_7_Campaign_10_AEM}          xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[7]/coral-multifield-item-content/div/div/div[2]/div/div[1]/coral-select/button/span
${selected_order_7_Badge_7_Campaign_10_AEM}          xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[7]/coral-multifield-item-content/div/div/div[2]/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[7]
${input_Badge Title - EN_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[7]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[2]/input[1]
${input_Badge Title - TH_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[7]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[3]/input[1]
${input_Badge Display_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[7]/coral-multifield-item-content[1]/div[1]/div[1]/div[2]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]

#Reward Store#AEM_Campaign_10 '10  Type of Content'
${btn_Add_7_Type of Content_Campaign_10_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/button/coral-button-label
${select_Type of Content_8_Campaign_10_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[8]/coral-multifield-item-content/div/div/div[1]/coral-select/button/span
${selected_Reward Store_Type of Content_8_Campaign_10_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[8]/coral-multifield-item-content/div/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[3]
${select_order_Reward Store_8_Campaign_10_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[8]/coral-multifield-item-content/div/div/div[3]/div/div[1]/coral-select/button/span
${selected_order_8_Reward Store_8_Campaign_10_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[8]/coral-multifield-item-content/div/div/div[3]/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[8]
${input_Reward Store Title - EN_Campaign_10_AEM}     xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[8]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[2]/input[1]
${input_Reward Store Title - TH_Campaign_10_AEM}     xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[8]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[3]/input[1]
${input_Reward Store_Campaign_10_AEM}     xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[8]/coral-multifield-item-content[1]/div[1]/div[1]/div[3]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]


#Article#AEM_Campaign_10 '10  Type of Content'
${btn_Add_8_Type of Content_Campaign_10_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/button/coral-button-label
${select_Type of Content_9_Campaign_10_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[9]/coral-multifield-item-content/div/div/div[1]/coral-select/button/span
${selected_Article_Type of Content_9_Campaign_10_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[9]/coral-multifield-item-content/div/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[5]
${select_order_Article_9_Campaign_10_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[9]/coral-multifield-item-content/div/div/div[7]/div/div[1]/coral-select/button/span
${selected_order_9_Article_9_Campaign_10_AEM}     xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[9]/coral-multifield-item-content/div/div/div[7]/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[9]
${input_Article Title - EN_Campaign_10_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[9]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[2]/input[1]
${input_Article Title - TH_Campaign_10_AEM}          xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[9]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[3]/input[1]
${input_Article Page - EN_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[9]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[4]/foundation-autocomplete[1]/div[1]/div[1]/input[1]
${input_Article Page - TH_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[9]/coral-multifield-item-content[1]/div[1]/div[1]/div[7]/div[1]/div[5]/foundation-autocomplete[1]/div[1]/div[1]/input[1]


#Link Out URL#AEM_Campaign_10 '10  Type of Content'
${btn_Add_9_Type of Content_Campaign_10_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/button/coral-button-label
${select_Type of Content_10_Campaign_10_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[10]/coral-multifield-item-content/div/div/div[1]/coral-select/button/span
${selected_Link Out URL_Type of Content_10_Campaign_10_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[10]/coral-multifield-item-content/div/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[6]
${select_order_Link Out URL_10_Campaign_10_AEM}          xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[10]/coral-multifield-item-content/div/div/div[4]/div/div[1]/coral-select/button/span
${selected_order_10_Link Out URL_10_Campaign_10_AEM}          xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[10]/coral-multifield-item-content/div/div/div[4]/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[10]
${input_Header - EN_URL_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[10]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[2]/input[1]
${input_Header - TH_URL_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[10]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[3]/input[1]
${input_URL - EN_URL_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[10]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[4]/input[1]
${input_URL - TH_URL_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[10]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[5]/input[1]
${input_Free Text - EN_URL_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[10]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[6]/div[1]/div[2]/p[1]
${input_Free Text - TH_URL_Campaign_10_AEM}           xpath=/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/coral-tabview[1]/coral-panelstack[1]/coral-panel[2]/coral-panel-content[1]/div[1]/div[1]/div[8]/div[1]/coral-multifield[1]/coral-multifield-item[10]/coral-multifield-item-content[1]/div[1]/div[1]/div[4]/div[1]/div[7]/div[1]/div[2]/p[1]

#AEM_Campaign_21_Rmove 9 Type of Content
${btn_delete_1_Type of Content_Campaign_21_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[1]/button[1]/coral-icon
${btn_delete_2_Type of Content_Campaign_21_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[2]/button[1]/coral-icon
${btn_Add_3_Type of Content_Campaign_21_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/button/coral-button-label
${input_Free Text - EN_Campaign_21_AEM}          xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[3]/coral-multifield-item-content/div/div/div[6]/div/div[2]/div/div[2]/p
${input_Free Text - TH_Campaign_21_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[3]/coral-multifield-item-content/div/div/div[6]/div/div[3]/div/div[2]/p

#AEM_Campaign_25_Rmove 9 Type of Content
${btn_delete_Type of Content_Campaign_22_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/button[1]/coral-icon
${Btn_Unpublish Page_Seasonal_Campaign_AEM}           xpath=/html/body/div[3]/div[2]/div[1]/coral-actionbar/coral-actionbar-primary/coral-actionbar-item[3]/coral-popover/div[3]/coral-popover-content/div/button[5]/coral-button-label
${Btn_Confirm_Unpublish Page_Seasonal_Campaign_AEM}           xpath=/html/body/coral-dialog/div[2]/coral-dialog-footer/button[2]/coral-button-label
${select_Type of Campaign_Campaign_22_AEM}        xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[1]/coral-select/button/span
${selected_Type Opt-in Campaign_Campaign_22_AEM}       xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[1]/coral-select/coral-overlay/coral-selectlist/coral-selectlist-item[3]
${btn_Add_Type of Content_Campaign_22_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[9]/div/coral-multifield/button/coral-button-label
${input_Free Text - EN_Campaign_22_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[9]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[2]/div/div[2]/div/div[2]/p
${input_Free Text - TH_Campaign_22_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[9]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[2]/div/div[3]/div/div[2]/p


#Publish Page
${Btn_Publish Page_Seasonal_Campaign_AEM}           xpath=/html/body/div[3]/div[2]/div[1]/coral-actionbar/coral-actionbar-primary/coral-actionbar-item[3]/coral-popover/div[3]/coral-popover-content/div/button[4]/coral-button-label
${Btn_Publish_Campaign_AEM}           xpath=/html/body/form/div/div/coral-panelstack/coral-panel/coral-panel-content/div/button/coral-button-label
${Btn_Publish_Seasonal_Campaign_AEM}           xpath=/html/body/form/div/div/coral-panelstack/coral-panel/coral-panel-content/div/button/coral-button-label
${Link_Publish API_Seasonal_Campaign_AEM}           xpath=/html[1]/body[1]/div[2]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/a[1]
${Text_AEM_01}          {"titleEn":"Campaign 1 EN","titleTh":"Campaign 1 TH","ispaginate":true,"featureImageEn":"https://uatlibrary.the1.co.th/content/dam/campaign/Prudential_400x400.jpg","featureImageTh":"https://uatlibrary.the1.co.th/content/dam/campaign/Prudential_400x400.jpg","pageStartDate":"01/10/2020","pageEndDate":"31/10/2020","pageType":"Seasonal","currentPage":1,"totalPages":1,"data":[{"order":"1","freetextEn":"\u003Cp\u003EFree Text - EN\u003C/p\u003E\r\n\u003Cp\u003E&nbsp;\u003C/p\u003E\r\n","freetextTh":"\u003Cp\u003EFree Text - TH\u003C/p\u003E\r\n\u003Cp\u003E&nbsp;\u003C/p\u003E\r\n"}]}
${Max allowed items is 10}           xpath=//*[@id="coral-id-5"]/coral-panel-content/div/div/div[8]/div/coral-icon
${Image_Max allowed items is 10}           xpath=//*[@id="label_e4d7cae4-2ded-4225-8519-5811458de369"]
${Order value exists. Modify value}           xpath=//*[@id="coral-collection-id-9"]/coral-multifield-item[2]/coral-multifield-item-content/div/div/div[6]/div/div[1]/coral-icon
${Can't Change Camapaign Type}           xpath=//*[@id="coral-id-8"]
${Max allowed items is 5}                xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[5]/div/div[3]/coral-icon
${Max allowed items is 5_Campaign_Fail_AEM}                xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item/coral-multifield-item-content/div/div/div[5]/div/div[2]/coral-icon
${btn_Add_Type of Content_Campaign_Fail_AEM}           xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/button/coral-button-label
${Max allowed items is 10_Campaign_Fail_AEM}            xpath=/html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-icon
${Order value exists. Modify value_Campaign_Fail_AEM}           xpath=//html/body/div[1]/div[2]/div/div/form/div/coral-tabview/coral-panelstack/coral-panel[2]/coral-panel-content/div/div/div[8]/div/coral-multifield/coral-multifield-item[3]/coral-multifield-item-content/div/div/div[6]/div/div[1]/coral-icon
